### ISSUE TITLE
Где id, вес, калории, описание и всё остальное?

### ISSUE THREAD

**Issue by coursar** [RenatFaiz/KFC#2]
https://github.com/RenatFaiz/KFC/blob/f2be910b93702f1aaafe3035a4ad5fcf17cf7af0/src/main/java/kfc/Burger.java#L4-L6

**Comment by RenatFaiz** [comment]
В классе Main. В д/з было задание создать пару объектов класса, описывающих бургеры. Я это и сделал.
https://github.com/RenatFaiz/KFC/blob/master/src/main/java/kfc/Main.java

**Comment by coursar** [comment]
В классе Main нет ни id, ни веса, ни того, что указано здесь.

В задании было - написать классы, описывающие бургеры со страницы.

В ваших классах явно не хватает полей для описания бургеров со страницы.

**Comment by RenatFaiz** [comment]
Понял, Ильназ. Я сначала подумал, что необязательно описывать все поля (или почти все поля), поэтому выбрал только три.  Вообщем, исправил)
